{ pkgs, config, ... }: {
  windowrulev2 = [
    "float, class:^(pavucontrol)$"
    "float, class:^(blueman-manager)$"
    "float, class:^(nm-connection-editor)$"
    "float, class:^(thunar)$"
    "float, class:^(polkit-gnome-authentication-agent-1)$"
    "float, title:^(Open)$"
    "float, class:^(xdg-desktop-portal-gtk)$"
    "float, class:^(xdg-desktop-portal-kde)$"
    "float, class:^(Thunar)$"
    "float, class:^(kitty)$,title:^(top)$"
    "float, class:^(kitty)$,title:^(btop)$"
    "float, class:^(kitty)$,title:^(htop)$"
    "float, class:^(kitty)$,title:^(gotop)$"
    "float, class:^(vlc)$"
    "float, class:^(mpv)$"
    "float, class:^(kvantummanager)$"
    "float, class:^(qt5ct)$"
    "float, class:^(qt6ct)$"
    "float, class:^(nwg-look)$"
    "float, class:^(org.pulseaudio.pavucontrol)$"
    "float, class:^(pavucontrol)$"
    "float, class:^(blueman-manager)$"
    "float, class:^(nm-applet)$"
    "float, class:^(nm-connection-editor)$"
    "float, class:^(polkit-gnome-authentication-agent-1)$"
    "float, class:^(lxpolkit)$"
    "float, class:^(Color Picker)$"
    "float, class:^(org.gnome.font-viewer)$"
    "noblur,class:^()$,title:^()$"
    "float,class:^(xdg-desktop-portal-gtk)$"
    "opacity 0.9 0.9, class:^(cursor)$"
    "opacity 0.9 0.9, class:^(Code)$"
    "opacity 0.7 0.7, class:^(kitty)$"
    "opacity 0.85 0.85, class:^(Spotify)$"
  ];
  windowrules = [
    "float,title:^(Open)$"
    "float,title:^(Choose Files)$"
    "float,title:^(Save As)$"
    "float,title:^(Confirm to replace files)$"
    "float,title:^(File Operation Progress)$"
    "suppressevent maximize, class:.*"
    "nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0"
  ];
}
