windowrulev2 = float,title:^(Open)$
windowrulev2 = float,title:^(Choose Files)$
windowrulev2 = float,title:^(Save As)$
windowrulev2 = float,title:^(Confirm to replace files)$
windowrulev2 = float,title:^(File Operation Progress)$
windowrulev2 = float,title:^(Properties)$
windowrulev2 = float,title:^(Progress)$
windowrulev2 = float,title:^(Picture-in-Picture)$
windowrulev2 = float,title:^(Select files)$
windowrulev2 = float,title:^(Select a folder)$
windowrulev2 = float,title:^(Select a file)$
windowrulev2 = float,title:^(Select a directory)$
windowrulev2 = float,title:^(Select a file or directory)$
windowrulev2 = float,class:^(vivaldi-stable)$,title:^(Sign in - Google Accounts - Vivaldi)$

windowrulev2 = float,class:^(xdg-desktop-portal-gtk)$
windowrulev2 = float,class:^(xdg-desktop-portal-kde)$
windowrulev2 = float,size 850 600,class:^(thunar)$
windowrulev2 = float,size 800 600,class:^(Spotify)$
windowrulev2 = float,class:^(kitty)$,title:^(top|btop|htop|gotop)$
windowrulev2 = float,class:^(vlc)$
windowrulev2 = float,class:^(mpv)$
windowrulev2 = float,class:^(kvantummanager|qt5ct|qt6ct|nwg-look)$
windowrulev2 = float,class:^(org.pulseaudio.pavucontrol|pavucontrol)$
windowrulev2 = float,class:^(blueman-manager|nm-applet|nm-connection-editor)$
windowrulev2 = float,class:^(org.kde.polkit-kde-authentication-agent-1|lxpolkit)$
windowrulev2 = float,class:^(Color Picker|org.gnome.font-viewer)$

windowrulev2 = float,center,title:^(Rename.*)$
windowrulev2 = float,center,class:^(xarchiver)$,title:^(Create a new archive)$

windowrulev2 = opacity 0.9 0.9,class:^(Cursor)$
windowrulev2 = opacity 0.9 0.9,class:^(Code - Insiders)$
windowrulev2 = opacity 0.9 0.9,class:^(kitty)$
windowrulev2 = opacity 0.9 0.9,class:^(Spotify)$

windowrulev2 = suppressevent maximize,class:.*

#windowrulev2 = opacity 0.8 0.8, class:.*

#windowrulev2=noblur,class:^()$,title:^()$
#windowrule = suppressevent maximize, class:.*
#windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0 
